[package]
name = "tuassiff"
authors = ["TaXi0k"]
repository = "https://github.com/TaXi0k/tuassiff"
license = "CC BY-NC 4.0"
description = "Tuassiff is a bespoke, unoptimized, custom binary image serialization file format."
readme = "README.md"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.10"
